### ISSUE TITLE
Create an R spatial object rather than a gg object to enhance mapping capacity 

### ISSUE THREAD

**Issue by trashbirdecology** [pdil/usmap#31]
Please correct me if I am wrong here, but the only spatial features I see in the maps are to obtain the CRS, and transform the object to a data frame (but not an SPDF). I see there is an option to snap other data frames having the same CRS to the usmap (gg). 

Is there a simple way to back-transform the gg object to an SPDF or other spatial format outside gg universe?

**Comment by pdil** [comment]
It's been a while since this request was made but the next version of `usmap` should support this. The work has already been completed in [usmapdata](https://github.com/pdil/usmapdata) which now stores the map data as an `sf` object instead of a data frame. This should allow for much better shape data manipulation. The changes for `usmap` will be in version 0.7.0, hopefully releasing in the next month or so.

In the meantime you should be able to call `usmapdata::us_map(as_sf = TRUE)` as long as you're on `usmapdata 0.2.0` and you will get the map data as an `sf` object.
